name: hoagsource
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
#  sdk: ^3.5.1
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

# flutter_intl:
#   enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  path: ^1.9.0
  gap:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  recase: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/hoag/
    - assets/icons/outline/
    - assets/icons/solid/
    - assets/icons/mini/
    - assets/icons/micro/
